# Site settings
title: "PSKL"
description: "Generated ramblings"
baseurl: ""
url: "http://pascal.cc"
twitter_username: fullstache
github_username:  pskl

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Ruby gems
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
