# Site settings
title: Mint
description: "mostly tech schnaps"
baseurl: "/blog"
url: "http://pascal.cc"
twitter_username: fullstache
github_username:  pskl

# Build settings
markdown: kramdown
highlighter: pygments

# Ruby gems
gems:
  - jemoji
