# Site settings
title: Bananas and potatoes
description: mostly tech schnaps
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: http://pascal.cc
twitter_username: fullstache
github_username:  pskl

# Build settings
markdown: kramdown

gems:
  - jemoji
