# Site settings
title: "Bananas and potatoes"
description: mostly tech schnaps
baseurl: "/blog"
url: http://pascal.cc
twitter_username: fullstache
github_username:  pskl

# Build settings
markdown: kramdown
highlighter: rouge

# Ruby gems
gems:
  - jemoji
  - rouge
