# Site settings
title: "ᕼYᑭEᖇᔕᒪOᑭ"
description: "Ramblings of a software engineer"
baseurl: ""
url: "https://pascal.cc"
github_username: pskl

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Ruby gems
gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
