# Site settings
title: Devblog
email: pascal.lamouric@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tech stuff and others
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://pascal.cc # the base hostname & protocol for your site
twitter_username: fullstache
github_username:  pskl

# Build settings
markdown: kramdown

gems:
  - jemoji
